# Generated by Django 4.2.2 on 2023-07-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0011_alter_character_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image',
        ),
    ]
