# Generated by Django 4.2.2 on 2023-07-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0014_feat_item_spell'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=1),
        ),
    ]
