# Generated by Django 4.2.2 on 2023-07-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0016_character_alignment_character_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attunement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='properties',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.CharField(blank=True, max_length=6000),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
