# Generated by Django 4.2.2 on 2023-07-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0017_item_attunement_item_name_item_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
