# Generated by Django 4.2.2 on 2023-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0019_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='properties',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
