# Generated by Django 4.2.2 on 2023-07-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0020_alter_item_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.CharField(blank=True, max_length=9000),
        ),
    ]
