# Generated by Django 4.2.2 on 2023-07-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0022_alter_item_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='properties',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
