# Generated by Django 4.2.2 on 2023-07-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0024_alter_item_text_alter_item_value_alter_item_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='casting',
            field=models.CharField(default='Action', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='classes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='components',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='duration',
            field=models.CharField(default='Instantaneous', max_length=100),
        ),
        migrations.AddField(
            model_name='spell',
            name='higher_levels',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='level',
            field=models.CharField(default='Cantrip', max_length=7),
        ),
        migrations.AddField(
            model_name='spell',
            name='name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='optional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='spell',
            name='source',
            field=models.CharField(default='PHB', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spell',
            name='text',
            field=models.CharField(blank=True, max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
