# Generated by Django 4.2.2 on 2023-07-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0025_spell_casting_spell_classes_spell_components_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='higher_levels',
            new_name='higher',
        ),
        migrations.AlterField(
            model_name='spell',
            name='casting',
            field=models.CharField(max_length=20),
        ),
    ]
