# Generated by Django 4.2.2 on 2023-07-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0026_rename_higher_levels_spell_higher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='components',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
