# Generated by Django 4.2.2 on 2023-07-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0028_character_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='temp_inventory',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
