# Generated by Django 4.2.2 on 2023-07-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0030_character_spells'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='users_spells', to='sheet.spell'),
        ),
    ]
