# Generated by Django 4.2.2 on 2023-07-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0031_alter_character_spells'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='coin_copper',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='coin_gold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='coin_silver',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
