# Generated by Django 4.2.2 on 2023-08-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0032_character_coin_copper_character_coin_gold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='bonds',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='flaws',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='ideals',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='traits',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
