# Generated by Django 4.2.2 on 2023-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0033_character_bonds_character_flaws_character_ideals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inspiration',
            field=models.BooleanField(default=False),
        ),
    ]
