# Generated by Django 4.2.2 on 2023-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0034_character_inspiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='initiative',
            field=models.IntegerField(default=10),
        ),
    ]
