# Generated by Django 4.2.2 on 2023-08-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0035_character_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armorclass',
            field=models.IntegerField(default=10),
        ),
    ]
