# Generated by Django 4.2.2 on 2023-08-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0036_character_armorclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=30),
        ),
    ]
