# Generated by Django 4.2.2 on 2023-08-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0037_character_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='currenthp',
            field=models.IntegerField(default=1),
        ),
    ]
