# Generated by Django 4.2.2 on 2023-08-04 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0038_character_currenthp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.item')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='inventorylist',
            field=models.ManyToManyField(blank=True, related_name='users_inventorylist', through='sheet.CharacterItem', to='sheet.item'),
        ),
    ]
