# Generated by Django 4.2.2 on 2023-08-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0039_characteritem_character_inventorylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='inventory',
        ),
    ]
